apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: ghost:3.40-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 2368
#          env:
#            - name: url
#              value: https://blog.mmmanyfold.com
